In [2]:
import numpy as np
import random

In [26]:
# 5.3 (2)

rank = 0
matrix4x4 = np.array([0,0])
while rank !=1:
    matrix4x4 = np.array([[random.randint(0,3) for j in range(4)]for i in range(4)])
    rank = np.linalg.matrix_rank(matrix4x4, 0.0001)
print (rank)
print(matrix4x4)
    

1
[[3 3 3 0]
 [2 2 2 0]
 [1 1 1 0]
 [2 2 2 0]]


In [21]:
# 5.4

a = (1,5)
b = (2,8)
print(np.outer(a,b))

[[ 2  8]
 [10 40]]


In [37]:
# 5.5
# Вычислите смешанное произведение трех векторов:(1, 5, 0), (2, 8, 7) и (7, 1.5, 3)

a = np.array([1, 5, 0], float)
b = np.array([2, 8, 7], float)
c = np.array([7, 1.5, 3], float)
v = np.cross(a, b)
print(v)
print (np.inner(v, c))
w = np.cross(b, c)
print (np.inner(w, a))
print(w)

[35. -7. -2.]
228.5
228.5
[ 13.5  43.  -53. ]
